openapi: 3.0.1
info:
  title: loan-system-api
  version: 1.0.1
  license:
    name: MIT License
    url: 'https://mit-license.org/'
  description: |
    # Introduction
    This is a system API that integrates with a PostgreSQL database. The database stores information
    related to loans and the users who own the loans.
servers:
  - url: 'http://localhost:8090/loanms'
    description: local
  - url: 'http://apis-dev.nerd.com:443/loanms'
    description: development
tags:
  - name: users
    description: Operations related to users in the loan database.
  - name: loans
    description: Operations related to loans in the loan database.
  - name: loan_reqeust_schema
    x-displayName: Loan Request Schema
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/LoanRequestBody" />
  - name: loan_response_schema
    x-displayName: Loan Response Schema
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/LoanResponseBody" />
  - name: user_response_schema
    x-displayName: User Response Schema
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/UserResponseBody" />
x-tagGroups:
  - name: General
    tags:
      - users
      - loans
  - name: Schemas
    tags:
      - loan_reqeust_schema
      - loan_response_schema
      - user_response_schema
paths:
  /users/{userId}/loans/{loanId}:
    $ref: paths/users@{userId}@loans@{loanId}.yaml
  /users/{userId}/loans:
    $ref: paths/users@{userId}@loans.yaml
  /users:
    $ref: paths/users.yaml
  /users/{userId}:
    $ref: paths/users@{userId}.yaml
