openapi: 3.0.1
info:
  title: loan-system-api
  version: 1.0.1
  license:
    name: MIT License
  description: |
    # Introduction
    This is a system API that integrates with a PostgreSQL database. The database stores information
    related to loans and the users who own the loans.
servers:
  - url: http://localhost:8090/loanms
    description: local
  - url: http://apis-dev.nerd.com:443/loanms
    description: development
tags:
  - name: users
    description: Operations related to users in the loan database.
  - name: loans
    description: Operations related to loans in the loan database.
paths:
  /users/{userId}/loans/{loanId}:
    $ref: paths/users@{userId}@loans@{loanId}.yaml
  /users/{userId}/loans:
    $ref: paths/users@{userId}@loans.yaml
  /users:
    $ref: paths/users.yaml
  /users/{userId}:
    $ref: paths/users@{userId}.yaml
